### ISSUE TITLE
Lein jmh doesn't use source-paths when loading code

### ISSUE THREAD

**Issue by lfn3** [jgpc42/lein-jmh#4]
Hi there,

It seems like this plugin isn't using the `:source-paths` value from the `project.clj` file.

I've run into an issue with one of my projects where I can't access any functions from my namespaces in the `jmh.edn` file. Whenever I add a function from my a namespace in my project, `lein jmh` fails with:

```
java.lang.RuntimeException: value did not resolve to a fn: jmh-test-more-src.more-core/more-gen-fn
```

The project uses a maven style layout, where I've provided source-paths. (and `java-source-paths` but that doesn't seem related based on my repro below)

I've got a repo with a minimal reproduction here: https://github.com/lfn3/lein-jmh-source-path-issue-repro

**Comment by jgpc42** [comment]
Hello! Thank you for the interest. However, I think there might be an issue with the repro. 

Unless I'm missing something, the [more-core](https://github.com/lfn3/lein-jmh-source-path-issue-repro/blob/master/more-src/jmh_test_more_src/more_core.clj) file namespace declaration should be `(ns jmh-test-more-src.more-core)` not `(ns more-core)`. If it is changed to the former, the `lein jmh '{:file "jmh-other-src-files.edn"}'` task call works as expected.

The jmh-clojure library is attempting to `require` the `more-core` namespace, which should be at the root of the source path directory `more-src` in the repro project.

Please report back if this doesn't solve the issue on your side. Thanks again!

**Comment by lfn3** [comment]
Hey thanks for that, you were right, that was pretty boneheaded of me. 
I've pushed another commit to that repo, with Protocols and Records added, which seems to cause the same issue. 
I tested out the same stuff that I suspect the `jmh-other-src-files.edn` would generate in the repl, and it works fine there:

```
((fn [a-record] (inc (jmh-test.core/get-s a-record))) (jmh-test.core/make-a-record 1))
;=> 2
```

**Comment by jgpc42** [comment]
Okay, I see what the problem is now. This time the error is `form did not evaluate to a fn` instead of ` value did not resolve to a fn`. This is a misleading error, which is my fault. The error should have been reported as something like `could not find namespace 'jmh-test.core'`. I will report a better error message in a subsequent version. 

Anyway, to explain. For `:fn` expressions (i.e., ones that are not simply a var symbol), jmh-clojure must use `eval` to get the state/benchmark fn to be used in the JMH subprocess. The one from `jmh-other-src-files.edn` here is attempting to call a fn in a namespace that hasn't been required yet: `jmh-test.core`.

This can be fixed in two ways. The first being to dynamically load the namespace:

```clojure
{:benchmarks [{:fn (fn [a-record]
                     (let [f (ns-resolve (doto 'jmh-test.core require)
                                         'get-s)]
                       (inc (f a-record))))
               :args [:state/gen-fn]}]
 :states     {:gen-fn (fn []
                        (let [f (ns-resolve (doto 'jmh-test.core require)
                                            'make-a-record)]
                          (f 1)))}
 :options    {:jmh/default {:mode :single-shot}}}
```

This is okay for states, but it is not ideal for benchmarks, since this will likely affect the benchmark timing.

The second is to use var symbols. Something like:

```clojure
{:benchmarks [{:fn jmh-test.core/get-s-and-inc
               :args [:state/gen-fn]}]
 :states     {:gen-fn {:fn jmh-test.core/make-a-record
                       :args [:param/num]}}
 :params     {:num 1}
 :options    {:jmh/default {:mode :single-shot}}}
```

The above uses a simple var I added to the `jmh-test.core` namespace:

```clojure
(defn get-s-and-inc [a-record]
  (inc (get-s a-record)))
```

The above example files both work as expected.

Also, the benchmark was failing because it's `:args` was declared to take two `:state/gen-fn`, whereas the `:fn` only accepts a single argument. I used the `:fail-on-error true` option to show this, which probably should be on by default.

I hope the above is of use in getting your benchmark up and running. Please feel free to reply if anything isn't clear.

**Comment by lfn3** [comment]
That's great thanks for the info. I've got it working now so thanks very much.
